import { TMDbMovie } from "./types";

export const MOCK_MOVIES: TMDbMovie[] = [
  {
    id: 60625,
    name: "Succession",
    poster_path: "/e2X3oieXSPCxnkPncHoRyFuTkLO.jpg",
    backdrop_path: "/2M7TP6aPX0RjBQKxnFWwOXoYHCz.jpg",
    overview: "The Roy family is known for controlling the biggest media and entertainment conglomerate in the world. However, their world changes when their father steps down from the company.",
    vote_average: 8.9,
    vote_count: 5000,
    first_air_date: "2018-06-03",
    genre_ids: [18],
    media_type: "tv",
    popularity: 500,
    adult: false,
    original_language: "en",
  },
  {
    id: 1396,
    name: "Breaking Bad",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    overview: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family's future.",
    vote_average: 9.5,
    vote_count: 12000,
    first_air_date: "2008-01-20",
    genre_ids: [18, 80],
    media_type: "tv",
    popularity: 800,
    adult: false,
    original_language: "en",
  },
  {
    id: 66732,
    name: "Stranger Things",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop_path: "/rcA17r3hfHtRtLXywZvdFGdsMzL.jpg",
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    vote_average: 8.7,
    vote_count: 15000,
    first_air_date: "2016-07-15",
    genre_ids: [18, 9648, 10765],
    media_type: "tv",
    popularity: 1200,
    adult: false,
    original_language: "en",
  },
  {
    id: 87108,
    name: "Chernobyl",
    poster_path: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    backdrop_path: "/mn4ZHHRqHMVNmUHRijFAl1JDFqn.jpg",
    overview: "A dramatization of the true story of the 2019 nuclear disaster, one of the worst man-made catastrophes in history.",
    vote_average: 9.4,
    vote_count: 9000,
    first_air_date: "2019-05-06",
    genre_ids: [18, 36],
    media_type: "tv",
    popularity: 400,
    adult: false,
    original_language: "en",
  },
  {
    id: 1668,
    name: "Friends",
    poster_path: "/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
    backdrop_path: "/l0qVZIpXtIo7km9Saturn8hzCDZ.jpg",
    overview: "Six friends navigate the pitfalls of work, life and love in New York City.",
    vote_average: 8.4,
    vote_count: 10000,
    first_air_date: "1994-09-22",
    genre_ids: [35],
    media_type: "tv",
    popularity: 700,
    adult: false,
    original_language: "en",
  },
  {
    id: 238,
    title: "The Godfather",
    poster_path: "/3bhkrj58Vtu7enYsLegHnDcdh9b.jpg",
    backdrop_path: "/tmU7GeKVPlowEolC8CKSHnaFbui.jpg",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.",
    vote_average: 8.7,
    vote_count: 18000,
    release_date: "1972-03-14",
    genre_ids: [18, 80],
    media_type: "movie",
    popularity: 500,
    adult: false,
    original_language: "en",
  },
  {
    id: 680,
    title: "Pulp Fiction",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
    vote_average: 8.5,
    vote_count: 25000,
    release_date: "1994-09-10",
    genre_ids: [53, 80],
    media_type: "movie",
    popularity: 700,
    adult: false,
    original_language: "en",
  },
  {
    id: 155,
    title: "The Dark Knight",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/hkBaDkMWbLaf8B1lsWssByrQrzmY.jpg",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.",
    vote_average: 9.0,
    vote_count: 30000,
    release_date: "2008-07-14",
    genre_ids: [28, 80, 18],
    media_type: "movie",
    popularity: 900,
    adult: false,
    original_language: "en",
  },
  {
    id: 37165,
    name: "The Leftovers",
    poster_path: "/jP3AVkEuQ1oGVziBJJsLWZCOvYA.jpg",
    backdrop_path: "/2MzEAJPbgQXvHqwFw0WkXXeUBLi.jpg",
    overview: "What would the world look like if 2% of the global population suddenly vanished without explanation?",
    vote_average: 8.3,
    vote_count: 3000,
    first_air_date: "2014-06-29",
    genre_ids: [18, 9648],
    media_type: "tv",
    popularity: 200,
    adult: false,
    original_language: "en",
  },
  {
    id: 94954,
    name: "Normal People",
    poster_path: "/pFHEqusYoFABkVqP2z7vTj7bxOQ.jpg",
    backdrop_path: "/rz13bJfNUNBL3P9MbOc0YtKMzIm.jpg",
    overview: "The story of a complicated relationship between two teenagers, Marianne and Connell, from small-town west of Ireland as they navigate different worlds at Trinity College Dublin.",
    vote_average: 7.9,
    vote_count: 4000,
    first_air_date: "2020-04-26",
    genre_ids: [18, 10749],
    media_type: "tv",
    popularity: 350,
    adult: false,
    original_language: "en",
  },
  {
    id: 100758,
    name: "The Bear",
    poster_path: "/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg",
    backdrop_path: "/rKsiNxKjhWEwndOgWPs273QLMnx.jpg",
    overview: "A young chef from the fine dining world comes home to Chicago to run his family's sandwich shop.",
    vote_average: 8.7,
    vote_count: 7000,
    first_air_date: "2022-06-23",
    genre_ids: [18, 35],
    media_type: "tv",
    popularity: 600,
    adult: false,
    original_language: "en",
  },
  {
    id: 1434,
    name: "Fargo",
    poster_path: "/psTbJB7IW78bvHBOkQfNJhyqbuS.jpg",
    backdrop_path: "/z5yJBLisAasFBMRNKioBqfcAGVm.jpg",
    overview: "Various chronicles of deception, intrigue and murder in and around frozen Minnesota.",
    vote_average: 8.9,
    vote_count: 4500,
    first_air_date: "2014-04-15",
    genre_ids: [18, 35, 80],
    media_type: "tv",
    popularity: 380,
    adult: false,
    original_language: "en",
  },
  {
    id: 76479,
    name: "The Boys",
    poster_path: "/stTEycfG9928HYGEISBFaG1ngjM.jpg",
    backdrop_path: "/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg",
    overview: "A group of vigilantes sets out to take down corrupt superheroes who abuse their superpowers.",
    vote_average: 8.5,
    vote_count: 8000,
    first_air_date: "2019-07-26",
    genre_ids: [10765, 18, 10759],
    media_type: "tv",
    popularity: 750,
    adult: false,
    original_language: "en",
  },
  {
    id: 85271,
    name: "White Lotus",
    poster_path: "/b2P7FrCdXhAc0ILi9yOXBPABxsA.jpg",
    backdrop_path: "/vRiDlCfSFJAHJk3kWHy5MIHi17x.jpg",
    overview: "Follows the exploits of various guests and employees of an exclusive tropical resort.",
    vote_average: 7.9,
    vote_count: 2500,
    first_air_date: "2021-07-11",
    genre_ids: [18, 35],
    media_type: "tv",
    popularity: 480,
    adult: false,
    original_language: "en",
  },
  {
    id: 1408,
    name: "House M.D.",
    poster_path: "/3GrRgt6CiLIUXaxGuWMbP8YcBQH.jpg",
    backdrop_path: "/nYjzGCaxjCXMELjz7Ztf5Uln44O.jpg",
    overview: "An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases.",
    vote_average: 8.6,
    vote_count: 8000,
    first_air_date: "2004-11-16",
    genre_ids: [18],
    media_type: "tv",
    popularity: 450,
    adult: false,
    original_language: "en",
  },
  {
    id: 1402,
    name: "The Walking Dead",
    poster_path: "/n7PdMuNuboFaWe6jFhQmhJrMfYU.jpg",
    backdrop_path: "/v7EMRyQCdDK2gA9ETbVkXlRE7gU.jpg",
    overview: "Sheriff's deputy Rick Grimes wakes up from a coma to find a post-apocalyptic world dominated by flesh-eating zombies.",
    vote_average: 8.1,
    vote_count: 12000,
    first_air_date: "2010-10-31",
    genre_ids: [10759, 10765, 18],
    media_type: "tv",
    popularity: 600,
    adult: false,
    original_language: "en",
  },
];

export const GENRE_MAP: Record<number, string> = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Sci-Fi",
  10770: "TV Movie",
  53: "Thriller",
  10752: "War",
  37: "Western",
  10759: "Action & Adventure",
  10762: "Kids",
  10763: "News",
  10764: "Reality",
  10765: "Sci-Fi & Fantasy",
  10766: "Soap",
  10767: "Talk",
  10768: "War & Politics",
};
